### ISSUE TITLE
EXISTS

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#10]
[EXISTS](https://redis.io/commands/exists/) returns if a key exists.

If a key exists it returns an integer value of 1 otherwise 0.
:0\r\n
:1\r\n

We can also ask for several keys
EXISTS key1 key2 key1 nosuchkey

In this case key1 will be counted 2 times so the answer will be:
:3\r\n

**Comment by RehasLiamsi** [comment]
Should we maybe create an instance of Jedispooled to connect to the redis database? Or should I go ahead with just the java method and code, i.e returning how many instances of the key exist?
