### ISSUE TITLE
HazeLists need to be correctly called 

### ISSUE THREAD

**Issue by cchriss123** [fungover/haze#101]
HazeLists need to be correctly called  correctly.
#17

**Comment by williamDenStore** [comment]
It might be easier to do this once the solutions to #17 and #38 has been merged into main and the issues has been closed. Since there might be some changes along the way?

**Comment by cchriss123** [comment]
> It might be easier to do this once the solutions to #17 and #38 has been merged into main and the issues has been closed. Since there might be some changes along the way?

Yeah well we are postponing or closing the  #38 for now so i will have to change that
#17 is mostly finished. Unless i mixed something it probably just need to be merged by Martin tomorrow.
