### ISSUE TITLE
Remove QUIT from return switch.

### ISSUE THREAD

**Issue by xCandyFun** [fungover/haze#126]
I think that it's better to remove QUIT from return switch on row 78.
Because according to the documentation https://redis.io/commands/quit/

"Note: Clients should not use this command. Instead, clients should simply close the connection when they're not used anymore. Terminating a connection on the client side is preferable, as it eliminates TIME_WAIT lingering sockets on the server side."

"As of Redis version 7.2.0, this command is regarded as deprecated.
It can be replaced by just closing the connection when migrating or writing new code."

**Comment by safstromo** [comment]
Good catch 👍 
Should be an easy fix.
