### ISSUE TITLE
Trying to start docker container fails.

### ISSUE THREAD

**Issue by safstromo** [fungover/haze#150]
**Describe the bug**
Trying to start docker container fails.

**To Reproduce**
Open terminal run command: 
docker run -p 6379:6379 fungover/haze

**Expected behavior**
Server starting

**Screenshots**

![Screenshot from 2023-02-17 11-54-21](https://user-images.githubusercontent.com/56272436/219628331-d0ecc009-4e6a-4400-8070-d8ff493b182c.png)

**Comment by kappsegla** [comment]
Reason for this is that we are missing libraries for log4j2 in our dockerfile. We need to copy the jar files for these dependencies when creating the docker image.

**Comment by kappsegla** [comment]
Step one, add maven plugin maven-dependency-plugin
Then update Dockerfile to copy dependencies from target/dependency
