### ISSUE TITLE
INCR DECR INCRBY DECRBY

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#16]
When storing values in a key that can be represented as a 64-bit signed integer we can perform addition and subtractions on the value. Incr will add one to the stored value and then return the new value as an integer.

[INCR](https://redis.io/commands/incr/)
[DECR](https://redis.io/commands/decr/)

If trying this on a key holding a value that can't be represented as an integer, an error will be returned.
-Error message\r\n 

value is not an integer or out of range

The first word after the "-", up to the first space or newline, represents the kind of error returned.
ERR is the generic error, while WRONGTYPE is a more specific error
-ERR unknown command 'helloworld'
-WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by jonathanjonathan001** [comment]
As written in the title, should the command INCRBY DECRBY be implemented as well?

**Comment by kappsegla** [comment]
> As written in the title, should the command INCRBY DECRBY be implemented as well?

I think they belong together as one implementation. INCR is just an alias for INCRBY key 1 so the actual implementation should probably be around INCRBY and then call that from INCR?
