### ISSUE TITLE
Refractor init methods from main to initialize

### ISSUE THREAD

**Issue by robinalfengard** [fungover/haze#185]
The main class should be kept as clean as possible. Right now there are several initilize methods in the main class which should be moved to the initialize class

**Comment by cmatlak** [comment]
I have done a pull request on this issue

**Comment by Mattan41** [comment]
I removed myself as a reviewer pull request #186 since i assigned to the PR and wrote some additional tests. We need one more review on the pull request.

**Comment by TrungMa1** [comment]
Keeping the main class tidy is key. Moving initialization methods to a separate class for clarity and easier maintenance. I did leave a review on the pull request and i think it looks great!
