### ISSUE TITLE
Bump version number for checkout action

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#211]
Old version of - uses: actions/checkout@v3 in maven.yml and sonar.yml and release.yml
Can be updated to v4 and we will get rid of warnings under each action when they are running:

**Build and analyze**
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Mattan41** [comment]
this issue should be closed with PR #215 beeing approved, correct?

**Comment by kappsegla** [comment]
Yes, closes #215
