### ISSUE TITLE
Add .editorConfig

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#28]
Add an [.editorconfig](https://editorconfig.org/) to your repo so your entire team is using the same code formatting standards.

[IntelliJ has builtin support for editorconfig.](https://www.jetbrains.com/help/idea/editorconfig.html)

What are the most important settings to have in the file for our java project?

**Comment by kappsegla** [comment]
Maybe we don't need this as long as all of us are using the same IDE with default settings?

**Comment by kappsegla** [comment]
[Standardize code styles](https://www.freecodecamp.org/news/how-to-use-editorconfig-to-standardize-code-styles/)

**Comment by kappsegla** [comment]
Should have settings for enforcing newline at file ending when saving.
insert_final_newline: Set to true ensure file ends with a newline when saving and false to ensure it doesn’t.
See comment in #36 for reason why.

**Comment by jLereback** [comment]
In Editor => Code style => Java, you can import a code scheme (.xlm) for the project, could that be an option instead of .editorconfig?

Are there any pros and cons?

**Comment by kappsegla** [comment]
> 

I think that xml style is an intellij specific and manual function while a .editorconfig will work on most IDEs out of the box?
