### ISSUE TITLE
Edit .gitignore

### ISSUE THREAD

**Issue by Ahlberg-iths** [fungover/haze#43]
We might have to adjust the .gitignore file a little bit if we want to ignore all of the files located in the .idea folder. Git still wants to track some of them. What do you all think about targeting `.idea/` to target all files in this folder?

<img width="542" alt="205925" src="https://user-images.githubusercontent.com/113943951/217092442-fd12e7de-4310-427e-8d2c-e6c66b8775c4.png">

**Comment by safstromo** [comment]
Go for it :)

**Comment by MikaelEdwartz** [comment]
I noticed that in another branch we have the sonarlint catalogue in .gitingore so if we switched to .idea/* in the gitignore folder I think we would miss out on sonarlint

**Comment by kappsegla** [comment]
Isn't sonarlint a local database for analyzes done locally? If we add that to git it will change all the time because it depends on which branch you are working.

**Comment by MikaelEdwartz** [comment]
Maybe unnecessary, I was reading [this](https://community.sonarsource.com/t/sonarlint-generated-files-visual-studio-2022-and-gitignore/56273), that commiting them might reduce potential clutter. That might be an issue related to VSC and Azure as stated in the link and not for this project?

**Comment by Svartkettil** [comment]
Based on your comments I think it's best to ignore sonarlint. Maybe if we would find it necessary to add sonarlint we could add it in a separate branch later?

**Comment by kappsegla** [comment]
Here are some tips from IntelliJ about what files to include and not from .idea folder. https://intellij-support.jetbrains.com/hc/en-us/articles/206544839
When using other editors these files doesn't make sense anyways and we have a maven project so when cloning the project the files in .idea folder will be automatically created. Versioning too many files will just end up with changes in these xml files in every commit which makes our code review harder.
