### ISSUE TITLE
Break line

### ISSUE THREAD

**Issue by jLereback** [fungover/haze#45]
In the main class (row 24), there are a line break written like this: \r\n

Isn't this style only used for windows machines? Should it be updated to \n?

![image](https://user-images.githubusercontent.com/112405931/217218927-868ff56d-1ef3-487c-87d0-6ba2bd2d5e93.png)

**Comment by signealfonson** [comment]
No, this is the standard way of RESP protocol line breaking.[
](https://redis.io/docs/reference/protocol-spec/#:~:text=In%20RESP%2C%20different%20parts%20of%20the%20protocol%20are%20always%20terminated%20with%20%22%5Cr%5Cn%22%20(CRLF))
