### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#50]
Since the application is a server application we would like some integration tests that can run to verify the behavior of the whole app. Starting a server and verifying that it accepts socket connections. 
But also tests for the individual functions that have been implemented. These command tests could be implemented in advance and ready to activate when the command is implemented. Or create some sort of template example test that can be copied and implemented by the assigneess implementing the command function. 

I see at least two possibilities for starting the server. One option is to run it as a java application. What can be a bit problematic then is the server port. If the server tries to start and fails because the server port is already used our tests will fail. Therefor we should probably start the server on a random unused port. That can be done by using 0 as port number but how do we find out which port to connect to from our tests then.
Another option could be to use [Testcontainers](https://www.testcontainers.org/) and actually build an image from Dockerfile and run that as a docker container?

**Comment by BobHogvall** [comment]
Might be preferable to put this in its own class, since we have a lot of tests. Just a reminder that the class name should end with "IT", since this will also simplify the process of running it with maven and such.
