### ISSUE TITLE
#58 Release-config error

### ISSUE THREAD

**Issue by MikaelEdwartz** [fungover/haze#58]
from [release-drafter](https://github.com/release-drafter/release-drafter), I believe our error message
![Screenshot 2023-02-08 at 13 43 43](https://user-images.githubusercontent.com/92143166/217532980-eb2a57b2-0588-47d4-b77b-8520ad449a98.jpg)

might be caused because missing 

![Screenshot 2023-02-08 at 13 44 13](https://user-images.githubusercontent.com/92143166/217533097-d087aade-1082-4017-a58e-91e18aa3fd76.jpg)

pull_request_target event

adding it might fix the problem

**Comment by kappsegla** [comment]
That's interesting because [here](https://github.com/redis/jedis/blob/master/.github/workflows/release-drafter.yml) the code is the same as ours?

**Comment by MikaelEdwartz** [comment]
> That's interesting because [here](https://github.com/redis/jedis/blob/master/.github/workflows/release-drafter.yml) the code is the same as ours?

Yes the code is the same, but in the commented code it says "pull_request_target event is required for autolabeler to support PR's from forks, and the types is opened, reopened, and synchronize.
Which our code doesn't include, and error message says that pull_request_target.reopened isnt a valid webhook.

Can the problem be caused by release_drafter trying to use it but since we don't have it in our yml file we get that it isn't a valid webhook?

**Comment by kappsegla** [comment]
@MikaelEdwartz after looking at some other projects it seems that this log message is printed always? But if someone of us are using PR from forks we might have to add more stuff to the config file. But is anyone doing that or are all of us pushing feature branches directly to this repo?
