### ISSUE TITLE
Update Maven plugin versions

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#7]
When running mvn help:effective-pom we can see the some plugins are using older versions and some are even missing for example the plugin for running integration tests failsafe is missing completely.
Add latest core plugins to the pom.xml. [Available Plugins](https://maven.apache.org/plugins/)

**Comment by RobertMili** [comment]
mvn versions:display-dependency-updates

**Comment by kappsegla** [comment]
> 

Does this work for dependencies coming from super pom?
