### ISSUE TITLE
Bug: Auto closing connection

### ISSUE THREAD

**Issue by jLereback** [fungover/haze#98]
When running Haze, the connection to the server is closed after each incoming command. 

![image](https://user-images.githubusercontent.com/112405931/218509866-08e8b0d5-99fd-4189-a5cd-1a474f672663.png)

It should close the connection when we want it to :)

**Comment by JesperBodin** [comment]
What do we need to do to ensure that the connection stays open?

**Comment by AntonLindskog96** [comment]
Is it possible to use a loop that continuously listens for incoming messages from the client? :)
